### ISSUE TITLE
symbolic not working with sympy 1.7

### ISSUE THREAD

**Issue by jose-matos** [cbm755/octsympy#1035]
I have fixed the most pressing issues identified with the connection to sympy 1.6 and now with the update to sympy 1.7 there are new issues raising:
```octave
>> a = syms('x')
Symbolic pkg v2.9.0: Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
AttributeError: '_PrintFunction' object has no attribute '__globals__'
Closing the Python communications link.

error: Python exception: AttributeError: '_PrintFunction' object has no attribute '__globals__'
    occurred in python_header import block.
    Try "sympref reset" and repeat your command?
    (consider filing an issue at https://github.com/cbm755/octsympy/issues)
error: called from
    pycall_sympy__ at line 191 column 5
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```

I would like to help fixing this. I will have some time after the second half of December. Are there any developer guide that can help me in this quest? :-)

**Comment by cbm755** [comment]
I think this is fixed, although there are still plenty of failing tests on 1.7.1

**Comment by Shadmeister** [comment]
Hi,
Although this bug is closed, the issue is not fixed. 

I am using Fedora 35, Octave 6.4, Symbolic 2.9.0, and SymPy 1.9.1, and the same issue as per initial report. 

I installed Octave as per the distro repositories, so did not want to reconfigure the system (if this is possible)

Regards,
Shadmeister.

**Comment by cbm755** [comment]
No new release has been made.  Issues are closed once they are fixed in the development source code.

We hope to have a long-overdue release early this summer.
