### ISSUE TITLE
symbolic not working with sympy 1.6

### ISSUE THREAD

**Issue by beew** [cbm755/octsympy#1023]
Symbolic is not compatible with sympy 1.6

```
>> pkg load symbolic
>> syms x
Symbolic pkg v2.9.0: /usr/local/lib/python3.8/dist-packages/sympy/__init__.py:672: SymPyDeprecationWarning:

importing sympy.core.compatibility with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.compatibility
instead. See https://github.com/sympy/sympy/issues/18245for more
info.

  self.Warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
  File "/usr/local/lib/python3.8/dist-packages/sympy/__init__.py", line 677, in __getattr__
    return getattr(self.mod, name)
AttributeError: module 'sympy.core.compatibility' has noattribute 'integer_types'
Waiting...............warning: readblock: timeout of 30 exceeded, breaking out
warning: called from
    readblock at line 101 column 7
    python_ipc_popen2 at line 99 column 16
    python_ipc_driver at line 62 column 15
    pycall_sympy__ at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
no output so far

error: ipc_popen2: something wrong? timed out starting python
error: called from
    python_ipc_popen2 at line 101 column 7
    python_ipc_driver at line 62 column 15
    pycall_sympy__ at line 163 column 11
    valid_sym_assumptions at line 38 column 10
    assumptions at line 82 column 7
    syms at line 97 column 13
```
Downgrade to sympy-1.5 with pip3 and it works again.

OS Ubuntu 20.04
Octave 5.2.0
symbolic 2.9.0 (as shown in the output above)
sympy 1.6 installed with pip

**Comment by cbm755** [comment]
Thanks!   Will try to get this fixed up and do a new release

**Comment by studentbrad** [comment]
Use the latest working version, SymPy 1.5.1 in the meantime.

**Comment by aherculanof123** [comment]
how can I install 

"sympy 1.6 installed with pip"

**Comment by cbm755** [comment]
For now I think you'll need to downgrade sympy, something like `pip install --user sympy==1.5.1`

**Comment by aherculanof123** [comment]
Thanks. It works again.

**Comment by scrouthtv** [comment]
Any update on this?

Still not working for me

**Comment by YousefSaber** [comment]
I also face the same issue 
```
>> syms x
Symbolic pkg v2.9.0: /usr/local/lib/python3.8/dist-packages/sympy/__init__.py:672: SymPyDeprecationWarning:

importing sympy.core.compatibility with 'from sympy import *' has been
deprecated since SymPy 1.6. Use import sympy.core.compatibility
instead. See https://github.com/sympy/sympy/issues/18245 for more
info.

  self.Warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in octoutput_drv
  File "<stdin>", line 54, in octoutput
  File "<stdin>", line 55, in octoutput
  File "/usr/local/lib/python3.8/dist-packages/sympy/__init__.py", line 677, in __getattr__
    return getattr(self.mod, name)
AttributeError: module 'sympy.core.compatibility' has no attribute 'integer_types'
```

**Comment by Notios** [comment]
> For now I think you'll need to downgrade sympy, something like `pip install --user sympy==1.5.1`

It's works!

**Comment by beew** [comment]
Just to update that it is still not fixed for sympy >= 1.6.

**Comment by vitaminace33** [comment]
> For now I think you'll need to downgrade sympy, something like `pip install --user sympy==1.5.1`

Workaround works on Manjaro 21.2rc where Octave 6.4.0 and SymPy 1.9 are installed.

@cbm755 Does PR #1051 closes this issue for 1.6 and above as stated?

Thx.

**Comment by vitaminace33** [comment]
[This](https://github.com/marshmallow-code/marshmallow/issues/1917#issuecomment-983789153) might also be of interest.
